// Shared input contract for the linked workbook and the plan renderer.
globalThis.HAIDE_FIELDS = [
  ["registered_address", "注册地址", "基本信息", "text", true],
  ["contract_q", "Q 合同编号", "基本信息"],
  ["contract_e", "E 合同编号", "基本信息"],
  ["contract_s", "S 合同编号", "基本信息"],
  ["management_representative", "管理者代表及职务", "基本信息"],
  ["representative_phone", "管理者代表电话", "基本信息"],
  ["contact_name", "联系人及职务", "基本信息", "text", true],
  ["contact_phone", "联系人电话", "基本信息", "text", true],
  ["contact_email", "联系人邮箱", "基本信息"],
  ["audit_systems", "体系组合（QMS,EMS,OHSMS）", "审核要求", "text", true],
  ["stage2_audit_type", "本次审核类型", "审核要求", "text", true],
  ["audit_type_detail", "各体系审核类型及监督次数", "审核要求"],
  ["changes", "变更事项（无变更填无）", "审核要求", "text", true],
  ["criteria_q", "Q 审核标准及版本", "审核要求"],
  ["criteria_e", "E 审核标准及版本", "审核要求"],
  ["criteria_s", "S 审核标准及版本", "审核要求"],
  ["criteria_extra", "其他审核准则", "审核要求"],
  ["scope_text_q", "Q 正式认证范围文字", "审核要求"],
  ["scope_text_e", "E 正式认证范围文字", "审核要求"],
  ["scope_text_s", "S 正式认证范围文字", "审核要求"],
  ["coverage_start_date", "审核覆盖起始日期", "审核要求", "date", true],
  ["coverage_end_date", "审核覆盖截止日期（空白为本次审核末日）", "审核要求", "date"],
  ["audit_method", "审核方式", "审核要求", "text", true],
  ["other_purpose", "其他目的（扩大/缩小/恢复/转换等）", "审核要求"],
  ["restore_suspended", "是否暂停恢复", "审核要求", "yesno"],
  ["stage2_person_days", "本次批准总现场审核人日", "时间安排", "number", true],
  ["stage1_start_date", "一阶段开始日期（适用时）", "时间安排", "date"],
  ["stage1_end_date", "一阶段结束日期（适用时）", "时间安排", "date"],
  ["stage1_person_days", "一阶段批准审核人日（适用时）", "时间安排", "number"],
  ["shift_date", "倒班审核日期（适用时）", "时间安排", "date"],
  ["shift_start", "倒班审核开始时间（适用时）", "时间安排", "time"],
  ["outsource_visit", "是否赴外包方现场审核", "场所及其他", "yesno"],
  ["outsource_details", "外包过程、单位、地址及审核安排", "场所及其他"],
  ["site_arrangements", "固定/临时多场所、地址、活动及分组安排", "场所及其他"],
  ["travel_arrangements", "转场日期、起止时间、人员代码及路线", "场所及其他"],
  ["schedule_notes", "日程补充说明（时段限制、特殊过程等）", "场所及其他"],
  ["mms_level", "MMS认证级别（适用时）", "场所及其他"],
  ["enms_boundary", "EnMS边界（适用时）", "场所及其他"],
  ["enp_boundary_relation", "EnP与EnMS边界相同/不同（适用时）", "场所及其他"],
  ["enp_boundary", "EnP核算边界（不同时填写）", "场所及其他"]
].map(([key, label, section, type = "text", required = false]) => ({ key, label, section, type, required }));
